// Your generated code here
// This file is auto-generated by elf-magic
// DO NOT EDIT - Assume changes will be lost.
//
// Build Status:
// ✓ spl_associated_token_account - SUCCESS
// ------------------------------------------------------------
// Constants
/// ELF binary for the spl_associated_token_account Solana program
pub const SPL_ASSOCIATED_TOKEN_ACCOUNT_ELF: &[u8] =
    include_bytes!(env!("SPL_ASSOCIATED_TOKEN_ACCOUNT_ELF_PATH"));

/// Get all available Solana program ELF binaries
/// Returns a vector of (program_name, elf_bytes) tuples
pub fn elves() -> Vec<(&'static str, &'static [u8])> {
    vec![(
        "spl_associated_token_account",
        SPL_ASSOCIATED_TOKEN_ACCOUNT_ELF,
    )]
}
