// Your generated code here
// This file is auto-generated by elf-magic
// DO NOT EDIT - Assume changes will be lost.
//
// Build Status:
// ✓ spl_elgamal_registry - SUCCESS
// ✓ spl_token_2022 - SUCCESS
// ------------------------------------------------------------
// Constants
/// ELF binary for the spl_elgamal_registry Solana program
pub const SPL_ELGAMAL_REGISTRY_ELF: &[u8] = include_bytes!(env!("SPL_ELGAMAL_REGISTRY_ELF_PATH"));

/// ELF binary for the spl_token_2022 Solana program
pub const SPL_TOKEN_2022_ELF: &[u8] = include_bytes!(env!("SPL_TOKEN_2022_ELF_PATH"));

/// Get all available Solana program ELF binaries
/// Returns a vector of (program_name, elf_bytes) tuples
pub fn elves() -> Vec<(&'static str, &'static [u8])> {
    vec![
        ("spl_elgamal_registry", SPL_ELGAMAL_REGISTRY_ELF),
        ("spl_token_2022", SPL_TOKEN_2022_ELF),
    ]
}
