// This file is auto-generated by elf-magic
// DO NOT EDIT MANUALLY - Changes will be overwritten
//
// Build Status:
// ✓ pinocchio_token_program - SUCCESS
// ✓ spl_token - SUCCESS
// ------------------------------------------------------------
// Constants
/// ELF binary for the pinocchio_token_program Solana program
pub const SPL_TOKEN_P_TOKEN_ELF: &[u8] = include_bytes!(env!("PINOCCHIO_TOKEN_PROGRAM_ELF_PATH"));

/// ELF binary for the spl_token Solana program
pub const SPL_TOKEN_PROGRAM_ELF: &[u8] = include_bytes!(env!("SPL_TOKEN_ELF_PATH"));

/// Get all available Solana program ELF binaries
/// Returns a vector of (program_name, elf_bytes) tuples
pub fn elves() -> Vec<(&'static str, &'static [u8])> {
    vec![
        ("pinocchio_token_program", SPL_TOKEN_P_TOKEN_ELF),
        ("spl_token", SPL_TOKEN_PROGRAM_ELF),
    ]
}
