
// This file is auto-generated by elf-magic
// DO NOT EDIT MANUALLY - Changes will be overwritten
//
// Build Status:
// ✓ p_memo - SUCCESS
// ✓ spl_memo - SUCCESS
// ------------------------------------------------------------
// Constants
/// ELF binary for the p_memo Solana program
pub const P_MEMO_ELF: &[u8] = include_bytes!(env!("P_MEMO_ELF_PATH"));

/// ELF binary for the spl_memo Solana program
pub const SPL_MEMO_ELF: &[u8] = include_bytes!(env!("SPL_MEMO_ELF_PATH"));

/// Get all available Solana program ELF binaries
/// Returns a vector of (program_name, elf_bytes) tuples
pub fn elves() -> Vec<(&'static str, &'static [u8])> {
    vec![
        ("p_memo", P_MEMO_ELF),
        ("spl_memo", SPL_MEMO_ELF),
    ]
}