
// This file is auto-generated by elf-magic
// DO NOT EDIT MANUALLY - Changes will be overwritten
//
// Build Status:
// ✓ solana_stake_program - SUCCESS
// ------------------------------------------------------------
// Constants
/// ELF binary for the solana_stake_program Solana program
pub const SOLANA_STAKE_PROGRAM_ELF: &[u8] = include_bytes!(env!("SOLANA_STAKE_PROGRAM_ELF_PATH"));

/// Get all available Solana program ELF binaries
/// Returns a vector of (program_name, elf_bytes) tuples
pub fn elves() -> Vec<(&'static str, &'static [u8])> {
    vec![
        ("solana_stake_program", SOLANA_STAKE_PROGRAM_ELF),
    ]
}